### ISSUE TITLE
[BUG] Value is changing on page load

### ISSUE THREAD

**Issue by tahir-asadov** [markmead/alpinejs-slug#5]
How can I make it only triggers when title changes.
The problem is I can't manually change the slug if I want to. It convert on page loads every time

**Comment by markmead** [comment]
You can just upload a video straight into GitHub comments, but I think I know what you mean and I believe I have a solution.

**Comment by markmead** [comment]
Fancy checking out the PR @tahir-asadov and seeing if it solves your issue? I basically had the same setup while testing so it should be A-OK! 🤞

**Comment by tahir-asadov** [comment]
Didn't work. I'm new to Alpine JS.
Maybe I'm doing something wrong.
I'll comment if I resolve the issue

**Comment by markmead** [comment]
Are you using the PR version and adding `.lazy`?

**Comment by markmead** [comment]
I've pushed that version to NPM, it's 1.1.1, change your `package.json` to use that version and install. It should be working.

**Comment by tahir-asadov** [comment]
`x-slug.lazy` fixed the issue.
Thank you.
